baseURL = "https://mrisdal.github.io/blog/"
publishDir = "docs"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License"
title = "Megan Risdal"
footnoteReturnLinkContents = "â†©"
theme = "base16"
sectionPagesMenu = "main"
pluralizeListTitles = "false"
googleAnalytics = "UA-127474557-1"

[author]
  name = "Megan Risdal" 
  email = "mrisdal@gmail.com"

[params]
  description = "Megan Risdal's personal website"
  images = ["img/hero.jpg"]

  [params.social]
    twitter = "meganrisdal"
    github = "mrisdal"

[permalinks]
  post = "/:year/:month/:title/"